In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('wine.csv')
data.head()

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0     1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1     1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2     1    13.16        2.36  2.67  18.6  101     2.80        3.24   
3     1    14.37        1.95  2.50  16.8  113     3.85        3.49   
4     1    13.24        2.59  2.87  21.0  118     2.80        2.69   

   Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                  0.28     2.29       5.64  1.04  3.92     1065  
1                  0.26     1.28       4.38  1.05  3.40     1050  
2                  0.30     2.81       5.68  1.03  3.17     1185  
3                  0.24     2.18       7.80  0.86  3.45     1480  
4                  0.39     1.82       4.32  1.04  2.93      735

In [5]:
pre = data.values
#output determine
Y = pre[:, 0]
#input determine
X = pre[:, 1:13]

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 20)

In [7]:
# Some features have higher means and standard deviations than others. This implies other data is not standardized.
# We need to standardize it to make it easier for the classifiers to work on.


from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [8]:
from sklearn.linear_model import Perceptron
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix


pnn = Perceptron(max_iter = 300, random_state = 1)
pnn.fit(X_train, Y_train)
y_pred = pnn.predict(X_test)
print("Accuracy score: " + str(accuracy_score(Y_test, y_pred)))
print("\nConfusion matrix: \n" + str(confusion_matrix(Y_test, y_pred)))
print("\nClassification report: \n" + str(classification_report(Y_test, y_pred)))

Accuracy score: 0.9777777777777777

Confusion matrix: 
[[13  0  0]
 [ 1 21  0]
 [ 0  0 10]]

Classification report: 
              precision    recall  f1-score   support

         1.0       0.93      1.00      0.96        13
         2.0       1.00      0.95      0.98        22
         3.0       1.00      1.00      1.00        10

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



In [9]:
from sklearn.neural_network import MLPClassifier

mpnn = MLPClassifier(hidden_layer_sizes=(150, 100),random_state = 1 , max_iter=300)

In [10]:
mpnn.fit(X_train, Y_train)
ym_pred = mpnn.predict(X_test)
print("Accuracy score: " + str(accuracy_score(Y_test, ym_pred)))
print("\nConfusion matrix: \n" + str(confusion_matrix(Y_test, ym_pred)))
print("\nClassification report: \n" + str(classification_report(Y_test, ym_pred)))

Accuracy score: 0.9777777777777777

Confusion matrix: 
[[13  0  0]
 [ 0 21  1]
 [ 0  0 10]]

Classification report: 
              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00        13
         2.0       1.00      0.95      0.98        22
         3.0       0.91      1.00      0.95        10

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

